### PR TITLE
Sw 136 level up system for pets

### PR DESCRIPTION
**Pull request by parchea**
Level up system is working on only on the pet page due to the broken share total xp after working out.

### CODE REVIEW

**Comment by parchea** [comment]
To test the xp leveling functionality just uncomment the button in the top of the pet page.

**Review by jtstanczak7 — APPROVED** [review]
Looks good so far

**Review by DanielEap — COMMENTED** [review]
Its good. documentation looks up to date, no actual conflicts

**Review by DanielEap — APPROVED** [review]
Good

**Pull request merged**
