### PR TITLE
milestone demo 2 testing

### PR DESCRIPTION
**Pull request by DanielEap**
**Please thoroughly review and add/subtract pieces you think are necessary**

### CODE REVIEW

**Review by dillon09776 — APPROVED** [review]
I followed the instructions provided to download and install the app through TestFlight without any issues.

**Review by jtstanczak7 — CHANGES_REQUESTED** [review]
I just updated the other elements to make sure they reflect current development. Please check to make sure everything looks good

**Review by AdamRa97 — APPROVED** [review]
lgtm

**Review by DanielEap — COMMENTED** [review]
changes already in main

**Pull request merged**
