### PR TITLE
Cloud kit assets codebase

### PR DESCRIPTION
**Pull request by DanielEap**

### CODE REVIEW

**Comment by DanielEap** [comment]
Only relevant code is the TestDB.swift file. The others are templates that I am  going to be using

**Review by SlowMiata — APPROVED** [review]
please add comments to your code. what am i reading?

**Review by jtstanczak7 — APPROVED** [review]
Implementation looks good but some comments would be useful for the future.

**Review by parchea — COMMENTED** [review]
Looking good, I like that the file presents a well structured approach to integrating CloudKit functionality.

**Review by parchea — APPROVED** [review]

**Review by dillon09776 — APPROVED** [review]
Great job on the database implementation!

**Pull request merged**
