### PR TITLE
Sw 137 cache login

### PR DESCRIPTION
**Pull request by AdamRa97**
Added login retention / login caching so user's don't need to constantly relogin after exiting the app after they already logged in previously.

### CODE REVIEW

**Review by SlowMiata — APPROVED** [review]
works with simulator, good job

**Review by DanielEap — APPROVED** [review]
simple if statement gets the job done, great work!

**Review by jtstanczak7 — APPROVED** [review]
Great change, looks good

**Review by parchea — APPROVED** [review]
Looking good :)

**Pull request merged**
