### PR TITLE
Added sharesheet functionality and combined it with the screenshot fu…

### PR DESCRIPTION
**Pull request by AdamRa97**
…nctionality. User should be able to do AirDrop, SaveImage, and etc

### CODE REVIEW

**Review by SlowMiata — APPROVED** [review]
I tested it, it works

**Review by DanielEap — APPROVED** [review]
cool

**Review by parchea — APPROVED** [review]
Good work

**Review by jtstanczak7 — APPROVED** [review]
Looks great and works perfectly

**Pull request merged**
