### PR TITLE
update ios version from 17.2 to 17.0

### PR DESCRIPTION
**Pull request by DanielEap**
change minimum iOS version from 17.2 ---> 17.0

### CODE REVIEW

**Review by SlowMiata — APPROVED** [review]
does this affect our XCode in any way?

**Comment by AdamRa97** [comment]
what's the reason for changing it to 17.0?

**Review by AdamRa97 — APPROVED** [review]
Lgtm

**Review by jtstanczak7 — APPROVED** [review]
Valid change, makes our app consistent with our documentation

**Pull request merged**
