### PR TITLE
Game Center and Achievement updates

### PR DESCRIPTION
**Pull request by jtstanczak7**
Check previous commits for more information

### CODE REVIEW

**Review by AdamRa97 — APPROVED** [review]
lgtm, needs to fix the merge conflicts first though

**Comment by SlowMiata** [comment]
you can merge testing into your own branch, fix the merge conflicts in vscode.

**Review by DanielEap — APPROVED** [review]
Coolio

**Review by dillon09776 — APPROVED** [review]
lgtm

**Pull request merged**
