### PR TITLE
Sw 147 fitness plan

### PR DESCRIPTION
**Pull request by jtstanczak7**
First iteration of fitness plan page that can be found in user settings. Also updated nav bar to say achievements instead of challenges.

### CODE REVIEW

**Review by parchea — APPROVED** [review]
This look great.

**Review by DanielEap — APPROVED** [review]
Great start, let me know how you plan to develop the top screen as it looks similar to the middle input portion

**Review by SlowMiata — APPROVED** [review]
I believe you are good to merge

**Comment by DanielEap** [comment]
** Let's NOT merge this until next sprint (4) **

**Pull request merged**
