### PR TITLE
Added screenshot functionality so that user can save an image of thei…

### PR DESCRIPTION
**Pull request by AdamRa97**
…r profile to their Photo Library to share with friends

### CODE REVIEW

**Review by DanielEap — APPROVED** [review]
saw the demo, looks great. Look forward to getting the share feature integrated

**Review by SlowMiata — APPROVED** [review]
I tested it and it works

**Review by jtstanczak7 — APPROVED** [review]
Looks great

**Review by SlowMiata — COMMENTED** [review]
just added code to crop the image

**Review by tun38646 — APPROVED** [review]
Camera screenshot functionality is working as tested. Might look into screenshottable views to get rid of the the navbar.

**Pull request merged**
