### PR TITLE
Displays health, food, and pet for new accounts

### PR DESCRIPTION
**Pull request by DanielEap**
To test, log into cloudKit, act as your personal iCloud account. Delete Records for: User, Pet, PetItem, FoodItem.
Delete and redownload app either through building or testflight. should work

### CODE REVIEW

**Review by parchea — APPROVED** [review]
Just tested and it work.

**Review by AdamRa97 — APPROVED** [review]
Let

**Review by SlowMiata — APPROVED** [review]
thanks for the fix

**Comment by SlowMiata** [comment]
Lets merge this first, then merge into development to make sure we have a working version before we merge the unit tests. Just in case something broke

**Pull request merged**
